prompt = "starship prompt"

[env]
AUTOJUMP_ERROR_PATH = "/Users/liuxiang/Library/autojump/errors.log"
AUTOJUMP_KEEP_SYMLINKS = "1"
AUTOJUMP_SOURCED = "1"
BARK_TOKEN = "nib2wzYd9Rouh53kbuDeEL"
BAT_CONFIG_PATH = "/Users/liuxiang/.config/.batrc"
CLICOLOR = "1"
CMD_DURATION = "877.613Âµs"
COLORFGBG = "15;0"
COLORTERM = "truecolor"
COMMAND_MODE = "unix2003"
CONFIGDIR = "/Users/liuxiang/.config"
DISPLAY = "/private/tmp/com.apple.launchd.R7fNnjHl92/org.macosforge.xquartz:0"
EDITOR = "emacsclient"
FPATH = "/Users/liuxiang/.rvm/scripts/zsh/Completion:/usr/local/share/zsh/site-functions:/Users/liuxiang/.oh-my-zsh/custom/plugins/fast-syntax-highlighting:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-completions:/Users/liuxiang/.oh-my-zsh/plugins/zsh_reload:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-brew-services:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-autosuggestions:/Users/liuxiang/.oh-my-zsh/plugins/cargo:/Users/liuxiang/.oh-my-zsh/custom/plugins/rustup:/Users/liuxiang/.oh-my-zsh/plugins/rust:/Users/liuxiang/.oh-my-zsh/plugins/minikube:/Users/liuxiang/.oh-my-zsh/plugins/kubectl:/Users/liuxiang/.oh-my-zsh/plugins/project-root:/Users/liuxiang/.oh-my-zsh/plugins/yum:/Users/liuxiang/.oh-my-zsh/plugins/xcode:/Users/liuxiang/.oh-my-zsh/plugins/virtualenv:/Users/liuxiang/.oh-my-zsh/plugins/vagrant:/Users/liuxiang/.oh-my-zsh/plugins/tmuxinator:/Users/liuxiang/.oh-my-zsh/custom/plugins/tmux-pane-words:/Users/liuxiang/.oh-my-zsh/plugins/tmux:/Users/liuxiang/.oh-my-zsh/plugins/tig:/Users/liuxiang/.oh-my-zsh/plugins/themes:/Users/liuxiang/.oh-my-zsh/plugins/terminitor:/Users/liuxiang/.oh-my-zsh/plugins/systemd:/Users/liuxiang/.oh-my-zsh/plugins/systemadmin:/Users/liuxiang/.oh-my-zsh/plugins/svn:/Users/liuxiang/.oh-my-zsh/plugins/screen:/Users/liuxiang/.oh-my-zsh/plugins/scala:/Users/liuxiang/.oh-my-zsh/plugins/sbt:/Users/liuxiang/.oh-my-zsh/plugins/safe-paste:/Users/liuxiang/.oh-my-zsh/plugins/rvm:/Users/liuxiang/.oh-my-zsh/plugins/ruby:/Users/liuxiang/.oh-my-zsh/plugins/rsync:/Users/liuxiang/.oh-my-zsh/plugins/rake:/Users/liuxiang/.oh-my-zsh/plugins/rails:/Users/liuxiang/.oh-my-zsh/plugins/pyenv:/Users/liuxiang/.oh-my-zsh/plugins/python:/Users/liuxiang/.oh-my-zsh/plugins/pip:/Users/liuxiang/.oh-my-zsh/plugins/perl:/Users/liuxiang/.oh-my-zsh/plugins/osx:/Users/liuxiang/.oh-my-zsh/plugins/nvm:/Users/liuxiang/.oh-my-zsh/plugins/npm:/Users/liuxiang/.oh-my-zsh/plugins/node:/Users/liuxiang/.oh-my-zsh/plugins/mvn:/Users/liuxiang/.oh-my-zsh/plugins/lein:/Users/liuxiang/.oh-my-zsh/plugins/jruby:/Users/liuxiang/.oh-my-zsh/plugins/httpie:/Users/liuxiang/.oh-my-zsh/plugins/history:/Users/liuxiang/.oh-my-zsh/plugins/gradle:/Users/liuxiang/.oh-my-zsh/plugins/golang:/Users/liuxiang/.oh-my-zsh/plugins/github:/Users/liuxiang/.oh-my-zsh/plugins/git:/Users/liuxiang/.oh-my-zsh/plugins/gemcd:/Users/liuxiang/.oh-my-zsh/plugins/gem:/Users/liuxiang/.oh-my-zsh/plugins/funcfind:/Users/liuxiang/.oh-my-zsh/plugins/emoji:/Users/liuxiang/.oh-my-zsh/plugins/encode64:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-docker-aliases:/Users/liuxiang/.oh-my-zsh/plugins/docker-machine:/Users/liuxiang/.oh-my-zsh/plugins/docker-compose:/Users/liuxiang/.oh-my-zsh/plugins/docker:/Users/liuxiang/.oh-my-zsh/plugins/copybuffer:/Users/liuxiang/.oh-my-zsh/plugins/common-aliases:/Users/liuxiang/.oh-my-zsh/plugins/cpanm:/Users/liuxiang/.oh-my-zsh/plugins/cp:/Users/liuxiang/.oh-my-zsh/plugins/compleat:/Users/liuxiang/.oh-my-zsh/plugins/colorize:/Users/liuxiang/.oh-my-zsh/plugins/colored-man-pages:/Users/liuxiang/.oh-my-zsh/plugins/bundler:/Users/liuxiang/.oh-my-zsh/plugins/brew:/Users/liuxiang/.oh-my-zsh/custom/plugins/bd:/Users/liuxiang/.oh-my-zsh/custom/plugins/autopair:/Users/liuxiang/.oh-my-zsh/plugins/autojump:/Users/liuxiang/.oh-my-zsh/plugins/alibas:/Users/liuxiang/.oh-my-zsh/plugins/ack2:/Users/liuxiang/.oh-my-zsh/functions:/Users/liuxiang/.oh-my-zsh/completions:/scripts/zsh/Completion:/usr/local/share/zsh/site-functions:/Users/liuxiang/.oh-my-zsh/custom/plugins/fast-syntax-highlighting:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-completions:/Users/liuxiang/.oh-my-zsh/plugins/zsh_reload:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-brew-services:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-autosuggestions:/Users/liuxiang/.oh-my-zsh/plugins/cargo:/Users/liuxiang/.oh-my-zsh/custom/plugins/rustup:/Users/liuxiang/.oh-my-zsh/plugins/rust:/Users/liuxiang/.oh-my-zsh/plugins/minikube:/Users/liuxiang/.oh-my-zsh/plugins/kubectl:/Users/liuxiang/.oh-my-zsh/plugins/project-root:/Users/liuxiang/.oh-my-zsh/plugins/yum:/Users/liuxiang/.oh-my-zsh/plugins/xcode:/Users/liuxiang/.oh-my-zsh/plugins/virtualenv:/Users/liuxiang/.oh-my-zsh/plugins/vagrant:/Users/liuxiang/.oh-my-zsh/plugins/tmuxinator:/Users/liuxiang/.oh-my-zsh/custom/plugins/tmux-pane-words:/Users/liuxiang/.oh-my-zsh/plugins/tmux:/Users/liuxiang/.oh-my-zsh/plugins/tig:/Users/liuxiang/.oh-my-zsh/plugins/themes:/Users/liuxiang/.oh-my-zsh/plugins/terminitor:/Users/liuxiang/.oh-my-zsh/plugins/systemd:/Users/liuxiang/.oh-my-zsh/plugins/systemadmin:/Users/liuxiang/.oh-my-zsh/plugins/svn:/Users/liuxiang/.oh-my-zsh/plugins/screen:/Users/liuxiang/.oh-my-zsh/plugins/scala:/Users/liuxiang/.oh-my-zsh/plugins/sbt:/Users/liuxiang/.oh-my-zsh/plugins/safe-paste:/Users/liuxiang/.oh-my-zsh/plugins/rvm:/Users/liuxiang/.oh-my-zsh/plugins/ruby:/Users/liuxiang/.oh-my-zsh/plugins/rsync:/Users/liuxiang/.oh-my-zsh/plugins/rake:/Users/liuxiang/.oh-my-zsh/plugins/rails:/Users/liuxiang/.oh-my-zsh/plugins/pyenv:/Users/liuxiang/.oh-my-zsh/plugins/python:/Users/liuxiang/.oh-my-zsh/plugins/pip:/Users/liuxiang/.oh-my-zsh/plugins/perl:/Users/liuxiang/.oh-my-zsh/plugins/osx:/Users/liuxiang/.oh-my-zsh/plugins/nvm:/Users/liuxiang/.oh-my-zsh/plugins/npm:/Users/liuxiang/.oh-my-zsh/plugins/node:/Users/liuxiang/.oh-my-zsh/plugins/mvn:/Users/liuxiang/.oh-my-zsh/plugins/lein:/Users/liuxiang/.oh-my-zsh/plugins/jruby:/Users/liuxiang/.oh-my-zsh/plugins/httpie:/Users/liuxiang/.oh-my-zsh/plugins/history:/Users/liuxiang/.oh-my-zsh/plugins/gradle:/Users/liuxiang/.oh-my-zsh/plugins/golang:/Users/liuxiang/.oh-my-zsh/plugins/github:/Users/liuxiang/.oh-my-zsh/plugins/git:/Users/liuxiang/.oh-my-zsh/plugins/gemcd:/Users/liuxiang/.oh-my-zsh/plugins/gem:/Users/liuxiang/.oh-my-zsh/plugins/funcfind:/Users/liuxiang/.oh-my-zsh/plugins/emoji:/Users/liuxiang/.oh-my-zsh/plugins/encode64:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-docker-aliases:/Users/liuxiang/.oh-my-zsh/plugins/docker-machine:/Users/liuxiang/.oh-my-zsh/plugins/docker-compose:/Users/liuxiang/.oh-my-zsh/plugins/docker:/Users/liuxiang/.oh-my-zsh/plugins/copybuffer:/Users/liuxiang/.oh-my-zsh/plugins/common-aliases:/Users/liuxiang/.oh-my-zsh/plugins/cpanm:/Users/liuxiang/.oh-my-zsh/plugins/cp:/Users/liuxiang/.oh-my-zsh/plugins/compleat:/Users/liuxiang/.oh-my-zsh/plugins/colorize:/Users/liuxiang/.oh-my-zsh/plugins/colored-man-pages:/Users/liuxiang/.oh-my-zsh/plugins/bundler:/Users/liuxiang/.oh-my-zsh/plugins/brew:/Users/liuxiang/.oh-my-zsh/custom/plugins/bd:/Users/liuxiang/.oh-my-zsh/custom/plugins/autopair:/Users/liuxiang/.oh-my-zsh/plugins/autojump:/Users/liuxiang/.oh-my-zsh/plugins/alibas:/Users/liuxiang/.oh-my-zsh/plugins/ack2:/Users/liuxiang/.oh-my-zsh/functions:/Users/liuxiang/.oh-my-zsh/completions:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.8/functions:/usr/local/share/zsh/site-functions:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-completions/src:/usr/local/share/zsh/site-functions:/usr/local/share/zsh/site-functions:/Users/liuxiang/.oh-my-zsh/custom/plugins/zsh-completions/src"
FZF_DEFAULT_OPTS = "-x -m --history=/Users/liuxiang/.fzf_history --history-size=10000 --bind 'ctrl-n:down,ctrl-p:up,alt-n:next-history,alt-p:previous-history,ctrl-l:jump,alt-a:select-all,ctrl-alt-j:half-page-down,ctrl-alt-k:half-page-up,alt-j:page-down,alt-k:page-up',ctrl-t:top"
FZF_TMUX = "1"
FZF_TMUX_HEIGHT = "40%"
GEM_HOME = "/Users/liuxiang/.rvm/gems/ruby-3.0.0"
GEM_PATH = "/Users/liuxiang/.rvm/gems/ruby-3.0.0:/Users/liuxiang/.rvm/gems/ruby-3.0.0@global"
GO111MODULE = "auto"
GOPATH = "/Users/liuxiang/.go"
GOROOT = "/usr/local/opt/go/libexec/"
GREP_COLOR = "\u001B[43;30"
GROOVY_HOME = "/usr/lib/groovy"
HOME = "/Users/liuxiang"
HOMEBREW_BAT = "1"
HOMEBREW_BOTTLE_DOMAIN = "https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
IRBRC = "/Users/liuxiang/.rvm/rubies/ruby-3.0.0/.irbrc"
ITERM2_COOKIE = "df819b32c680243666e78de88b5b2b98"
ITERM_PROFILE = "Default"
ITERM_SESSION_ID = "w1t0p0:A941C667-592B-4775-B4E1-8A8788DF5F95"
JENV_LOADED = "1"
LANG = "zh_CN.UTF-8"
LC_TERMINAL = "iTerm2"
LC_TERMINAL_VERSION = "3.4.6"
LESS = "-R"
LESSOPEN = "|/usr/local/bin/lesspipe.sh %s"
LESS_ADVANCED_PREPROCESSOR = "1"
LESS_TERMCAP_mb = "\u001B[05;34m"
LESS_TERMCAP_md = "\u001B[01;34m"
LESS_TERMCAP_me = "\u001B[0m"
LESS_TERMCAP_se = "\u001B[0m"
LESS_TERMCAP_so = "\u001B[44;33m"
LESS_TERMCAP_ue = "\u001B[0m"
LESS_TERMCAP_us = "\u001B[04;33m"
LOGNAME = "liuxiang"
LSCOLORS = "exfxcxdxcxegedabagacad"
LS_COLORS = "di=01;36"
LaunchInstanceID = "C9802067-8ABF-4B1D-9EE4-E37FBACAA14D"
MAGICK_HOME = "/opt/local"
MY_RUBY_HOME = "/Users/liuxiang/.rvm/rubies/ruby-3.0.0"
NULLCMD = ":"
NVM_CD_FLAGS = "-q"
NVM_DIR = "/Users/liuxiang/.nvm"
OLDPWD = "/Users/liuxiang/Library/Application Support/JetBrains"
PAGER = "less -R"
PERL5LIB = "/Users/liuxiang/perl5/lib/perl5"
PERL_MB_OPT = "--install_base \"/Users/liuxiang/perl5\""
PERL_MM_OPT = "INSTALL_BASE=/Users/liuxiang/perl5"
PWD = "/Users/liuxiang/tmp"
PYENV_ROOT = "/Users/liuxiang/.pyenv"
PYSPARK_DRIVER_PYTHON = "ipython"
RI = "-f ansi"
RUBY_VERSION = "ruby-3.0.0"
RUSTUP_DIST_SERVER = "https://mirrors.tuna.tsinghua.edu.cn/rustup"
RUST_SRC_PATH = "/usr/local/Cellar/rust/1.38.0/share/rust/rust_src"
SDKMAN_DIR = "/Users/liuxiang/.sdkman"
SECURITYSESSIONID = "186ab"
SHLVL = "2"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.ep06v5USgY/Listeners"
STARSHIP_SESSION_KEY = "1013322608279652"
TERM = "screen-256color"
TERM2NARROW = "false"
TERM_PROGRAM = "tmux"
TERM_PROGRAM_VERSION = "3.2"
TERM_SESSION_ID = "w1t0p0:A941C667-592B-4775-B4E1-8A8788DF5F95"
TMPDIR = "/var/folders/c7/8cxdcxpj5yg8n_282qjhkg4m0000gp/T/"
TMUX = "/private/tmp/tmux-502/default,7586,3"
TMUX_PANE = "%14"
TMUX_PLUGIN_MANAGER_PATH = "/Users/liuxiang/.tmux/plugins/"
TMUX_VERSION_MAJOR = "3"
TMUX_VERSION_MINOR = "2"
USER = "liuxiang"
VIRTUAL_ENV_DISABLE_PROMPT = "1"
VISUAL = "/Users/liuxiang/bin/emacsclient-for-visual"
XAPIAN_CJK_NGRAM = "1"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE = "fg=8"
ZSH_THEME_TERM_TAB_TITLE_IDLE = "%20<..<%~%<<"
ZSH_TMUX_CONFIG = "/Users/liuxiang/.tmux.conf"
ZSH_TMUX_TERM = "screen-256color"
_ = "/usr/local/bin/nu"
_ZSH_TMUX_FIXED_CONFIG = "/Users/liuxiang/.oh-my-zsh/plugins/tmux/tmux.extra.conf"
__CFBundleIdentifier = "com.googlecode.iterm2"
__CF_USER_TEXT_ENCODING = "0x1F6:0x19:0x34"
curl_ca_bundle = "/Users/liuxiang/.mitmproxy/mitmproxy-ca.pem"
rvm_alias_expanded = ""
rvm_bin_flag = ""
rvm_bin_path = "/Users/liuxiang/.rvm/bin"
rvm_docs_type = ""
rvm_gemstone_package_file = ""
rvm_gemstone_url = ""
rvm_hook = ""
rvm_niceness = ""
rvm_nightly_flag = ""
rvm_only_path_flag = ""
rvm_path = "/Users/liuxiang/.rvm"
rvm_prefix = "/Users/liuxiang"
rvm_pretty_print_flag = ""
rvm_proxy = ""
rvm_quiet_flag = ""
rvm_ruby_bits = ""
rvm_ruby_file = ""
rvm_ruby_make = ""
rvm_ruby_make_install = ""
rvm_ruby_mode = ""
rvm_script_name = ""
rvm_sdk = ""
rvm_silent_flag = ""
rvm_use_flag = ""
rvm_version = "1.29.10-next (master)"
STARSHIP_SHELL = "nu"
STARSHIP_CONFIG = "/Users/liuxiang/.config/starship.nushell.toml"