# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
#    author-name:
#    author-email:
#    copyright:
#    github-username:
package-indices:
  - name: USTC
    download-prefix: https://mirrors.ustc.edu.cn/hackage/package/
    http: https://mirrors.ustc.edu.cn/hackage/01-index.tar.gz
setup-info: "http://mirrors.ustc.edu.cn/stackage/stack-setup.yaml"
urls:
  latest-snapshot: http://mirrors.ustc.edu.cn/stackage/snapshots.json
  lts-build-plans: http://mirrors.ustc.edu.cn/stackage/lts-haskell/
  nightly-build-plans: http://mirrors.ustc.edu.cn/stackage/stackage-nightly/
